## Beispiel mit Zuständen

Viel besser gelungen ist mir die folgende Lösung.
Hier wurde sämtliche Builderlogik in separate Klassen ausgelagert und dadurch sollte sich hier der Einsatz von Annotation Prozessoren deutlich mehr lohnen. Eine Unschönheit besitzt aber auch diese Lösung. Um die im Aufbau befindliche
Instanz von einer Stage zur nächsten zu übertragen, ist der Aufruf einer Methode notwendig. Der Name diese Methode
würde sich normalerweise nach dem Klassennamen des aufzubauenden Objektes richten z.B. getPerson. Der Name würde dann
auch der korrekten Semantik entsprechen. Da aber über diese Methode das aufzubauende Objekt zugänglich gemacht wird,
würde eine getPerson() Methode aber einen Getter darstellen und somit das Builder Pattern verletzen. Beim Builder
Pattern gibt es nur eine Methode, welche das aufzubauende Objekt zurückgeben darf und das ist die build() Methode.
Daher wurde die Methode auch so benannt.

Leider muss diese build() Methode nun intern beim Stage Wechsel benutzt werden um das bisher erstellte Objekt weiter
zu geben. Das ist die Unschönheit an dieser Lösung.


[source,java]
.PlantumlEntityDiagramBuilder.java
----
include::../../main/java/com/github/huluvu424242/e4plantumldiagram/PlantumlEntityDiagramBuilder.java[lines=28..-1]
----

[source,java]
.BuilderStage.java
----
include::../../main/java/com/github/huluvu424242/e4plantumldiagram/BuilderStates.java[lines=28..-1]
----

Wieder zur xref:index.adoc[Übersicht] oder zurück zum xref:2states-example.adoc[Beispiel mit Zuständen].