name: Generate Docs

on:
  push:
  workflow_dispatch: {}

jobs:
#  build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK ${{ matrix.java-version }}
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'zulu'
#          java-version: ${{ matrix.java-version }}
#          java-package: jdk
#          cache: 'maven'
#
#      - name: Build with Maven
#        run: ./mvnw -Pgenerate-docs

  new_docs:
    permissions:
      id-token: write # Enable OIDC
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    name: Make a new pull request
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}
          java-package: jdk
          cache: 'maven'
      - uses: chainguard-dev/actions/setup-gitsign@main
      - name: Generate docs with Maven
        shell: bash
        run: ./mvnw -Pgenerate-docs

      - name: Push generated docs with git
        shell: bash
        run: git push

# ohne Push kann man auch einen PR erstellen
#      - name: Create Pull Request
#        uses: peter-evans/create-pull-request@v4.0.2
#        with:
#          title: "New generated docs PR!"

    strategy:
          matrix:
            java-version:
            - 19
